name: Desert Wind SUP
favicon: null
layout_spectrum: 0.82369
typography_spectrum: 0.07885
title: 'Desert Wind SUP - Relaxation, Fitness, and FUN!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#f67f21'
    - '#fef200'
    - '#0060aa'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
