typography_spectrum: 0.07283
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#f67f21'
    - '#fef200'
    - '#0060aa'
  brandStrength: 0.336993
  lightness: 0.5625
  rhythmicContrast: 0.75
  saturation: 0.4375
opengraph: {}
layout_spectrum: 0.39801
analytics: {}
name: Desert Wind SUP
cta: {}
title: Desert Wind SUP
purpose: []
