typography_spectrum: 0.07283
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#f67f21'
    - '#fef200'
    - '#0060aa'
  brandStrength: 0.336993
  lightness: 0.5625
  rhythmicContrast: 0.75
  saturation: 0.4375
opengraph: {}
layout_spectrum: 0.39801
analytics: {}
author:
  name: Rob Gibbs
  email: Rob@desertwindsailboats.com
name: Desert Wind SUP
cta: {}
navigation:
  - name: About
    id: 4ae13d76-746f-4825-811d-7b62bc34fb58
    type: content
title: Desert Wind SUP
description: Finding SUP in the Beauty of the Desert
purpose: []
