name: Desert Wind SUP
favicon: null
layout_spectrum: 0.90656
typography_spectrum: 0.62975
title: 'Relaxation, Fitness, and FUN!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#44b3e4'
    - '#f26e45'
    - '#767676'
  brandStrength: 0.375
  lightness: 0.4245979394763708
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
