analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#f67f21'
    - '#fef200'
    - '#0060aa'
  brandStrength: 0.336993
  lightness: 0.5625
  rhythmicContrast: 0.75
  saturation: 0.4375
cta: {}
layout_spectrum: 0.39801
name: Desert Wind SUP
opengraph: {}
purpose: []
typography_spectrum: 0.07283
