typography_spectrum: 0.33099540579132736
color:
  brandColors:
    - '#000000'
    - '#44B3E4'
    - '#F9EE4D'
    - '#F26E45'
    - '#767676'
  brandStrength: 0.8737099829595536
  lightness: 0.9561963479500264
  rhythmicContrast: 0.21943077445030212
  saturation: 0.3824195978231728
opengraph: {}
layout_spectrum: 0.2113855225034058
analytics: {}
author:
  name: Rob Gibbs
  email: Rob@desertwindsailboats.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7240cba6-0401-482e-b36e-622b1cc6d745.jpg
name: Desert Wind SUP
cta: {}
title: Desert Wind SUP
description: Finding SUP in the Beauty of the Desert
purpose: []
