name: Desert Wind SUP
favicon: null
layout_spectrum: 0.65852
typography_spectrum: 0.62975
title: 'Relaxation, Fitness, and FUN!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#44b3e4'
    - '#f26e45'
    - '#767676'
  brandStrength: 0.6875
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
