name: Desert Wind SUP
favicon: null
layout_spectrum: 0.39801
typography_spectrum: 0.07042
title: 'Desert Wind SUP - Relaxation, Fitness, and FUN!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#f67f21'
    - '#fef200'
    - '#0060aa'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
